In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.optimize import linprog  
import cvxpy as cp

Punto 1

In [2]:
df1 = pd.DataFrame({' ' : ['Materia prima','Mano de obra', 'Capital', 'Ganancia por ud'],
        'Product A' : [1, 2, 1, 3],
        'Product B' : [1, 4, 2, 5]})
df1

                    Product A  Product B
0    Materia prima          1          1
1     Mano de obra          2          4
2          Capital          1          2
3  Ganancia por ud          3          5

In [25]:
c = np.array([3, 5])

# Restricciones de desigualdad
A = np.array([[1, 1],
                  [2,4],
                    [1,2]])
b = np.array([5000,1000,2000])

# Bounds on decision variables
bounds1 = [(100, None),
           (150, None)]

# Solve the problem:
res1 = linprog(-c, A_ub=A, b_ub=b,
                  bounds=bounds1, method='revised simplex')

print(-res1.fun)
pd.DataFrame(res1.x).round(4).T

1350.0

<ipython-input-25-b005491f71a6>:14: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res1 = linprog(-c, A_ub=A, b_ub=b,

       0      1
0  200.0  150.0

In [ ]:
##La asignación optima que maximiza que maximiza las ganancias es 200 unidades de A y 150 unidades de B, esto da una ganancia de 1350 dolares.

Punto 2

In [8]:
c1=np.array([0.10,0.15,0.16,0.08])

A1= np.array([[0.5,0.3,0.25,0.6],
                [0.3,0.1,0.4,0.2],
                [0.2,0.6,0.35,0.2]])

A2=np.array([0.35,0.30,0.15])

A3=np.array([(1,1,1,1)])
A4=np.array([1])

res2=linprog(-c1,A_ub=-A,b_ub=-A2,A_eq=A3,b_eq=A4,method="simplex")
pd.DataFrame(res2.x).round(4).T

<ipython-input-8-bea942b5ab62>:12: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res2=linprog(-c1,A_ub=-A,b_ub=-A2,A_eq=A3,b_eq=A4,method="simplex")

     0       1       2       3
0  0.0  0.1579  0.5789  0.2632

In [17]:
#CVXPY
n=4
x = cp.Variable(n)
objetivo= cp.Minimize(-c1.T@x)
restriccion=[cp.sum(x)==1,A@x >=A2,x>=0]
prob=cp.Problem(objetivo,restriccion)
result=prob.solve()

scion2=pd.DataFrame(x.value)
pd.DataFrame(scion2).round(4).T

# Print result.
print(-prob.value)
pd.DataFrame(round(pd.DataFrame(x.value),4)).T

0.13736842087092851

     0       1       2       3
0  0.0  0.1579  0.5789  0.2632

In [ ]:
##Para maximizar el retorno esperado se debe invertir 15.79% en el fondo 1, 57,89% en el fondo 2 y 26.32 en el fondo 3.
##La ganancia maxima es de 13.74 dolares.

Punto 3

In [15]:
# Parameters 
r1 = 0.01
r2 = 0.02
r3 = 0.003

# Restricciones de desigualdad
c3= np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,1])
A3= np.array([[1,0,0,0,0,1,0,0,-1,0,0,0,0,0],
              [-1-r1,1,0,0,0,0,1,0,1+r3,-1,0,0,0,0],
              [0,-1-r1,1,0,0,0,0,1,0,1+r3,-1,0,0,0],
              [0,0,-1-r1,1,0,-1-r2,0,0,0,0,1+r3,-1,0,0],
              [0,0,0,-1-r1,1,0,-1-r2,0,0,0,0,1+r3,-1,0],
              [0,0,0,0,-1-r1,0,0,-1-r2,0,0,0,0,1+r3,-1]])

b3=np.array([150,100,-200,200,-50,-300])

A4 = np.array([[1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

A5 = np.array([100])

res3 = linprog(-c3, A_ub=-A4, b_ub=-A5, A_eq=A3, b_eq=b3,
              
              method='revised simplex') 
pd.DataFrame(res3.x).round(4).T

<ipython-input-15-6665d863ffb6>:21: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res3 = linprog(-c3, A_ub=-A4, b_ub=-A5, A_eq=A3, b_eq=b3,

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,0.0,0.0,0.0,52.0,150.0,100.0,151.9442,0.0,0.0,351.9442,0.0,0.0,92.4969

In [19]:
##CVXPY
n=14
x = cp.Variable(n)
objetivo2 = cp.Minimize(-c3.T@x)
restriccion2 = [x>=0,A3@x>=b3]
prob=cp.Problem(objetivo2,restriccion2)
result=prob.solve()

# Print result.
print(-prob.value)
print(round(pd.DataFrame(x.value),4).T)

92.49694912403417
    0        1    2    3        4      5        6         7    8    9   \
0  0.0  41.0006  0.0  0.0  10.1794  150.0  58.9994  193.3547  0.0  0.0

         10   11   12       13
0  351.9442  0.0  0.0  92.4969

In [ ]:
##El saldo maximo en el mes 6 es 92.4969 millones.

Punto 4

In [27]:
#Función objetivo 
c4 = np.array([0, 0, 0, 0, 0, 0, 0, 1])                                     
#Restricciones de desigualdad
rn = (1.0001)**7                                                              
A4 = np.array([[1, 0, 0, 0, -1, 0, 0, 0],
              [0, 1, 0, 0, rn, -1, 0, 0],
              [0, 0, 1, 0, 0, rn, -1, 0],
              [0, 0, 0, 1, 0, 0, rn, -1]])
b4 = np.array([[150, -100, -50, 200]])
##Función de optimizacion
res4 = linprog(-c4, A_ub=A4, b_ub=-b4, method='simplex')

print(-res4.fun)
pd.DataFrame(res4.x).round(4).T

200.14021366142958

<ipython-input-27-676dda933fa6>:11: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res4 = linprog(-c4, A_ub=A4, b_ub=-b4, method='simplex')

     0    1    2    3      4       5       6         7
0  0.0  0.0  0.0  0.0  150.0  50.105  0.1401  200.1402

In [ ]:
##La rentabilidad maxima es de 0.14 millones de pesos.

Punto 5

In [36]:
c = np.array([0,0,0,5,8,10])
A = np.array([[0,0,0,1,0,0],
              [0,1,0,0,0,0],
              [0,0,1,0,0,0],
              [0,0,0,0,1,0],
              [0,0,0,0,0,1]])
B=np.array([2000,300,250,2000,6000])

A2=np.array([[1,1,1,0,0,0],
             [0,0,0,1,1,1]])
B2= np.array([1000,10000])

res5 = linprog(-c, A_ub=A, b_ub=B, A_eq=A2, b_eq=B2, method="simplex")

print(-res5.fun)
pd.DataFrame(res5.x).round(4).T

86000.0

<ipython-input-36-c6fb0e1bcd87>:13: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res5 = linprog(-c, A_ub=A, b_ub=B, A_eq=A2, b_eq=B2, method="simplex")

       0      1      2       3       4       5
0  450.0  300.0  250.0  2000.0  2000.0  6000.0

In [ ]:
##La maxima ganancia posible es de $86000, para esto se invierten $2000 en ventas, $2000 en marketing y $6000 en producción.

ounto 6